name: Translation Check

on: 
  pull_request_target:
    paths:
     - 'data/language/**.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  Get Pull Request
        uses: actions/checkout@v7
        with:
          path: pr
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          allow-unsafe-pr-checkout: true

      - name: get en-GB.txt (curl)
        run: |
          mkdir -p OpenRCT2/data/language
          curl -sSLf https://raw.githubusercontent.com/OpenRCT2/OpenRCT2/develop/data/language/en-GB.txt -o OpenRCT2/data/language/en-GB.txt

      - name: Checkout translations before PR changes (for comparsion)
        uses: actions/checkout@v7
        with:
          path: master
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
          allow-unsafe-pr-checkout: true

      - name: Checkout commit before branch changes
        id: merge-base-commit
        run: |
          echo "head sha: ${{github.event.pull_request.head.sha}}"
          cd master
          git remote add upstream https://github.com/${{github.repository}}
          git fetch upstream
          merge_base=$(git merge-base refs/remotes/upstream/master HEAD)
          echo "merge base sha: ${merge_base}"
          git checkout $merge_base
          echo "merge_base=$merge_base" >> $GITHUB_OUTPUT
          cd ..

      - name: Print debug stuff
        run: |
          echo ${{steps.merge-base-commit.outputs.merge_base}}
          echo ${{github.event.pull_request.head.sha}}
          echo ${{steps.merge-base-commit.outputs.merge_base == github.event.pull_request.head.sha}}

      - name: Remove master
        if: ${{ steps.merge-base-commit.outputs.merge_base == github.event.pull_request.head.sha }}
        run: rm -rf master

      - name: Checkout upstream master as master
        uses: actions/checkout@v7
        if: ${{ steps.merge-base-commit.outputs.merge_base == github.event.pull_request.head.sha }}
        with:
          ref: master
          path: master
          allow-unsafe-pr-checkout: true

      - name: Set up Python 3.12
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Checkout upstream master (in order to use the newest version of the script)
        uses: actions/checkout@v7
        with:
          path: upstream_master
          ref: master
          allow-unsafe-pr-checkout: true

      - name: Run checks
        run: python upstream_master/.github/workflows/translation_check.py ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - id: get-comment-body
        run: |
          delimiter=$(openssl rand -hex 8)
          {
            echo "body<<$delimiter"
            cat result.md
            echo "$delimiter"
          } >> $GITHUB_OUTPUT

      - name: Create PR comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: ${{ steps.get-comment-body.outputs.body }}
